name: Setup Node.js
description: Common setup for Node.js projects with caching

inputs:
  install-playwright:
    description: Whether to install Playwright browsers
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Get Playwright version
      if: inputs.install-playwright == 'true'
      id: playwright-version
      shell: bash
      run: echo "version=$(npm ls @playwright/test --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      if: inputs.install-playwright == 'true'
      id: playwright-cache
      uses: actions/cache@v5
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install chromium --with-deps
